toolbar:
  -styleselect | bold italic | undo redo
  -image | link
plugins:
  -image
  -link

alternate:
  selector: textarea.table-editor
  toolbar: styleselect | bold italic | undo redo | table | image | link
  plugins:
    -table
  theme: modern